import type { DsaPattern, DsaPatternId, DsaProblem } from "./types";

export const DSA_PATTERNS: DsaPattern[] = [
  {
    id: "arrays-hashing",
    name: "Arrays & Hashing",
    description: "Frequency maps, prefix sums, and O(1) lookups.",
    week: 1,
    icon: "#",
  },
  {
    id: "two-pointers",
    name: "Two Pointers",
    description: "Sorted arrays, palindromes, and pair sums.",
    week: 1,
    icon: "↔",
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    description: "Subarrays, substrings, and fixed/variable windows.",
    week: 1,
    icon: "▭",
  },
  {
    id: "stack",
    name: "Stack",
    description: "Monotonic stacks, parentheses, and daily temperatures.",
    week: 1,
    icon: "⊟",
  },
  {
    id: "binary-search",
    name: "Binary Search",
    description: "Search space reduction on arrays and answers.",
    week: 1,
    icon: "⌕",
  },
  {
    id: "linked-list",
    name: "Linked List",
    description: "Fast/slow pointers, reversal, and merge patterns.",
    week: 2,
    icon: "⛓",
  },
  {
    id: "trees",
    name: "Trees",
    description: "DFS, BFS, BST properties, and recursion.",
    week: 2,
    icon: "T",
  },
  {
    id: "graphs",
    name: "Graphs",
    description: "BFS, DFS, topological sort, and shortest paths.",
    week: 2,
    icon: "◎",
  },
  {
    id: "heap",
    name: "Heap",
    description: "Top-K, merge K lists, and scheduling.",
    week: 2,
    icon: "△",
  },
  {
    id: "backtracking",
    name: "Backtracking",
    description: "Combinations, permutations, and constraint pruning.",
    week: 3,
    icon: "↩",
  },
  {
    id: "dynamic-programming",
    name: "Dynamic Programming",
    description: "1D/2D state, knapsack, and subproblem reuse.",
    week: 3,
    icon: "DP",
  },
  {
    id: "intervals",
    name: "Intervals",
    description: "Merge, insert, and meeting-room scheduling.",
    week: 3,
    icon: "∪",
  },
];

export const DSA_PROBLEMS: DsaProblem[] = [
  {
    id: "two-sum",
    title: "Two Sum",
    pattern: "arrays-hashing",
    difficulty: "Easy",
    week: 1,
    timeMinutes: 20,
    summary: "Return indices of two numbers that add to target.",
    constraints: ["2 ≤ n ≤ 10⁴", "Exactly one solution exists"],
    hints: [
      "Brute force is O(n²) — can you do better with extra space?",
      "Store value → index in a hash map as you scan.",
    ],
    approach: [
      "Iterate with complement = target - nums[i]",
      "If complement in map, return [map[complement], i]",
      "Else store nums[i] → i",
    ],
    complexity: { time: "O(n)", space: "O(n)" },
    leetcodeSlug: "two-sum",
    companies: ["Google", "Amazon", "Meta"],
  },
  {
    id: "valid-anagram",
    title: "Valid Anagram",
    pattern: "arrays-hashing",
    difficulty: "Easy",
    week: 1,
    timeMinutes: 15,
    summary: "Determine if two strings are anagrams.",
    constraints: ["Lowercase English letters only"],
    hints: ["Count character frequencies", "Or sort both strings and compare"],
    approach: ["Build freq map for s", "Decrement for t; any negative → false"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "valid-anagram",
    companies: ["Bloomberg", "Apple"],
  },
  {
    id: "group-anagrams",
    title: "Group Anagrams",
    pattern: "arrays-hashing",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 25,
    summary: "Group strings that are anagrams of each other.",
    constraints: ["Up to 10⁴ strings"],
    hints: ["Anagrams share the same sorted key or char-count signature"],
    approach: ["Map signature → list of words", "Return Object.values(map)"],
    complexity: { time: "O(n · k log k)", space: "O(n)" },
    leetcodeSlug: "group-anagrams",
    companies: ["Amazon", "Meta"],
  },
  {
    id: "valid-palindrome",
    title: "Valid Palindrome",
    pattern: "two-pointers",
    difficulty: "Easy",
    week: 1,
    timeMinutes: 15,
    summary: "Check if a string is a palindrome after removing non-alphanumeric.",
    constraints: ["Ignore case and non-alphanumeric"],
    hints: ["Two pointers from both ends", "Skip invalid chars inward"],
    approach: ["l=0, r=n-1; compare alnum chars; move pointers"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "valid-palindrome",
    companies: ["Microsoft", "Facebook"],
  },
  {
    id: "3sum",
    title: "3Sum",
    pattern: "two-pointers",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 35,
    summary: "Find all unique triplets that sum to zero.",
    constraints: ["No duplicate triplets in output"],
    hints: ["Sort first", "Fix i, then two-pointer on i+1..n-1"],
    approach: ["Sort nums", "For each i, two-sum with target -nums[i]", "Skip duplicates"],
    complexity: { time: "O(n²)", space: "O(1)" },
    leetcodeSlug: "3sum",
    companies: ["Google", "Amazon", "Apple"],
  },
  {
    id: "max-subarray",
    title: "Maximum Subarray",
    pattern: "sliding-window",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 25,
    summary: "Find contiguous subarray with largest sum (Kadane's).",
    constraints: ["At least one number"],
    hints: ["Track running sum; reset when negative", "Classic Kadane's algorithm"],
    approach: ["cur = max(nums[i], cur + nums[i])", "ans = max(ans, cur)"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "maximum-subarray",
    companies: ["LinkedIn", "Microsoft"],
  },
  {
    id: "longest-substring",
    title: "Longest Substring Without Repeating",
    pattern: "sliding-window",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 30,
    summary: "Length of longest substring with all unique characters.",
    constraints: ["ASCII characters"],
    hints: ["Variable window with char → last index map", "Shrink left when duplicate seen"],
    approach: ["Expand r, update map", "Move l past previous index of s[r]"],
    complexity: { time: "O(n)", space: "O(min(n, Σ))" },
    leetcodeSlug: "longest-substring-without-repeating-characters",
    companies: ["Amazon", "Bloomberg"],
  },
  {
    id: "valid-parentheses",
    title: "Valid Parentheses",
    pattern: "stack",
    difficulty: "Easy",
    week: 1,
    timeMinutes: 15,
    summary: "Determine if bracket string is valid.",
    constraints: ["Only '()[]{}'"],
    hints: ["Stack of opening brackets", "Pop on matching close"],
    approach: ["Push opens", "On close: pop must match", "Stack empty at end"],
    complexity: { time: "O(n)", space: "O(n)" },
    leetcodeSlug: "valid-parentheses",
    companies: ["Google", "Amazon"],
  },
  {
    id: "daily-temperatures",
    title: "Daily Temperatures",
    pattern: "stack",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 30,
    summary: "Days until a warmer temperature for each day.",
    constraints: ["Monotonic decreasing stack"],
    hints: ["Stack stores indices", "Pop while current temp > stack top"],
    approach: ["Monotonic stack of indices", "Fill answer on pop"],
    complexity: { time: "O(n)", space: "O(n)" },
    leetcodeSlug: "daily-temperatures",
    companies: ["Google", "Uber"],
  },
  {
    id: "search-rotated",
    title: "Search in Rotated Sorted Array",
    pattern: "binary-search",
    difficulty: "Medium",
    week: 1,
    timeMinutes: 30,
    summary: "Find target in rotated sorted array in O(log n).",
    constraints: ["No duplicates", "Distinct values"],
    hints: ["One half is always sorted", "Check which half contains target"],
    approach: ["Binary search with l,r", "Identify sorted half", "Narrow search space"],
    complexity: { time: "O(log n)", space: "O(1)" },
    leetcodeSlug: "search-in-rotated-sorted-array",
    companies: ["Meta", "Microsoft"],
  },
  {
    id: "reverse-linked-list",
    title: "Reverse Linked List",
    pattern: "linked-list",
    difficulty: "Easy",
    week: 2,
    timeMinutes: 20,
    summary: "Reverse a singly linked list iteratively or recursively.",
    constraints: ["O(n) time"],
    hints: ["Three pointers: prev, curr, next"],
    approach: ["Iterative: reverse links while walking", "Return prev as new head"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "reverse-linked-list",
    companies: ["Amazon", "Apple"],
  },
  {
    id: "merge-two-lists",
    title: "Merge Two Sorted Lists",
    pattern: "linked-list",
    difficulty: "Easy",
    week: 2,
    timeMinutes: 20,
    summary: "Merge two sorted linked lists into one sorted list.",
    constraints: ["Both lists sorted ascending"],
    hints: ["Dummy head simplifies pointer logic"],
    approach: ["Compare heads, attach smaller, advance", "Attach remainder"],
    complexity: { time: "O(n+m)", space: "O(1)" },
    leetcodeSlug: "merge-two-sorted-lists",
    companies: ["Microsoft", "Adobe"],
  },
  {
    id: "invert-binary-tree",
    title: "Invert Binary Tree",
    pattern: "trees",
    difficulty: "Easy",
    week: 2,
    timeMinutes: 15,
    summary: "Mirror a binary tree.",
    constraints: ["Recursive or iterative BFS/DFS"],
    hints: ["Swap left and right at each node"],
    approach: ["DFS: swap children, recurse", "Or BFS queue with swaps"],
    complexity: { time: "O(n)", space: "O(h)" },
    leetcodeSlug: "invert-binary-tree",
    companies: ["Google", "Homebrew"],
  },
  {
    id: "max-depth-tree",
    title: "Maximum Depth of Binary Tree",
    pattern: "trees",
    difficulty: "Easy",
    week: 2,
    timeMinutes: 15,
    summary: "Return max depth of a binary tree.",
    constraints: ["Tree has 0..10⁴ nodes"],
    hints: ["1 + max(left, right) recursively"],
    approach: ["Base: null → 0", "Return 1 + max(depth(left), depth(right))"],
    complexity: { time: "O(n)", space: "O(h)" },
    leetcodeSlug: "maximum-depth-of-binary-tree",
    companies: ["Amazon", "LinkedIn"],
  },
  {
    id: "level-order",
    title: "Binary Tree Level Order Traversal",
    pattern: "trees",
    difficulty: "Medium",
    week: 2,
    timeMinutes: 25,
    summary: "Return level-order traversal as list of lists.",
    constraints: ["BFS by level"],
    hints: ["Queue + track level size"],
    approach: ["BFS: process size nodes per level", "Push children for next level"],
    complexity: { time: "O(n)", space: "O(n)" },
    leetcodeSlug: "binary-tree-level-order-traversal",
    companies: ["Meta", "Microsoft"],
  },
  {
    id: "number-of-islands",
    title: "Number of Islands",
    pattern: "graphs",
    difficulty: "Medium",
    week: 2,
    timeMinutes: 30,
    summary: "Count connected components of '1's in a grid.",
    constraints: ["4-directional connectivity"],
    hints: ["DFS/BFS flood fill from each unvisited land cell"],
    approach: ["Scan grid; on '1', DFS mark visited and count++"],
    complexity: { time: "O(m·n)", space: "O(m·n)" },
    leetcodeSlug: "number-of-islands",
    companies: ["Amazon", "Google"],
  },
  {
    id: "course-schedule",
    title: "Course Schedule",
    pattern: "graphs",
    difficulty: "Medium",
    week: 2,
    timeMinutes: 35,
    summary: "Can you finish all courses given prerequisites?",
    constraints: ["Detect cycle in directed graph"],
    hints: ["Topological sort via Kahn's BFS or DFS cycle detection"],
    approach: ["Build adjacency + indegree", "Kahn's: process zero-indegree queue"],
    complexity: { time: "O(V+E)", space: "O(V+E)" },
    leetcodeSlug: "course-schedule",
    companies: ["Meta", "Amazon"],
  },
  {
    id: "kth-largest",
    title: "Kth Largest Element in Array",
    pattern: "heap",
    difficulty: "Medium",
    week: 2,
    timeMinutes: 25,
    summary: "Find kth largest element without full sort.",
    constraints: ["Quickselect or min-heap of size k"],
    hints: ["Min-heap of size k", "Or quickselect partition"],
    approach: ["Maintain min-heap size k", "Root is kth largest at end"],
    complexity: { time: "O(n log k)", space: "O(k)" },
    leetcodeSlug: "kth-largest-element-in-an-array",
    companies: ["Facebook", "Amazon"],
  },
  {
    id: "subsets",
    title: "Subsets",
    pattern: "backtracking",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 25,
    summary: "Return all possible subsets (power set).",
    constraints: ["Distinct integers"],
    hints: ["Include/exclude each element", "Or iterative build from subsets"],
    approach: ["Backtrack: push, recurse i+1, pop", "Copy path to result at each node"],
    complexity: { time: "O(n·2ⁿ)", space: "O(n)" },
    leetcodeSlug: "subsets",
    companies: ["Google", "Uber"],
  },
  {
    id: "combination-sum",
    title: "Combination Sum",
    pattern: "backtracking",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 30,
    summary: "Combinations that sum to target (reuse allowed).",
    constraints: ["Candidates distinct, reuse OK"],
    hints: ["Sort helps pruning", "Same start index to allow reuse"],
    approach: ["Backtrack from index i", "Subtract candidate, recurse i", "Prune when sum > target"],
    complexity: { time: "O(2^t)", space: "O(target)" },
    leetcodeSlug: "combination-sum",
    companies: ["Amazon", "Airbnb"],
  },
  {
    id: "climbing-stairs",
    title: "Climbing Stairs",
    pattern: "dynamic-programming",
    difficulty: "Easy",
    week: 3,
    timeMinutes: 15,
    summary: "Ways to climb n steps taking 1 or 2 at a time.",
    constraints: ["Fibonacci pattern"],
    hints: ["dp[i] = dp[i-1] + dp[i-2]"],
    approach: ["Rolling two variables a,b", "Iterate to n"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "climbing-stairs",
    companies: ["Adobe", "Apple"],
  },
  {
    id: "house-robber",
    title: "House Robber",
    pattern: "dynamic-programming",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 25,
    summary: "Max money robbing non-adjacent houses.",
    constraints: ["Linear street"],
    hints: ["At each house: rob + dp[i-2] or skip + dp[i-1]"],
    approach: ["prev2, prev1 rolling", "cur = max(prev1, nums[i]+prev2)"],
    complexity: { time: "O(n)", space: "O(1)" },
    leetcodeSlug: "house-robber",
    companies: ["Google", "Amazon"],
  },
  {
    id: "coin-change",
    title: "Coin Change",
    pattern: "dynamic-programming",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 35,
    summary: "Minimum coins to make amount (or -1).",
    constraints: ["Unlimited coins each denomination"],
    hints: ["dp[a] = min coins for amount a", "Iterate amounts 1..target"],
    approach: ["dp[0]=0, rest=∞", "For each coin, update dp[a] for a≥coin"],
    complexity: { time: "O(amount·n)", space: "O(amount)" },
    leetcodeSlug: "coin-change",
    companies: ["Amazon", "Bloomberg"],
  },
  {
    id: "merge-intervals",
    title: "Merge Intervals",
    pattern: "intervals",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 25,
    summary: "Merge all overlapping intervals.",
    constraints: ["Sort by start time"],
    hints: ["Sort intervals by start", "Merge if overlap with last in result"],
    approach: ["Sort", "If start ≤ last.end merge else push"],
    complexity: { time: "O(n log n)", space: "O(n)" },
    leetcodeSlug: "merge-intervals",
    companies: ["Google", "Meta", "Uber"],
  },
  {
    id: "meeting-rooms-ii",
    title: "Meeting Rooms II",
    pattern: "intervals",
    difficulty: "Medium",
    week: 3,
    timeMinutes: 35,
    summary: "Minimum conference rooms required.",
    constraints: ["Intervals [start, end]"],
    hints: ["Sort starts and ends separately", "Two pointers or min-heap of end times"],
    approach: ["Min-heap of end times", "If start ≥ heap.min pop else push end"],
    complexity: { time: "O(n log n)", space: "O(n)" },
    leetcodeSlug: "meeting-rooms-ii",
    companies: ["Amazon", "Google", "Bloomberg"],
  },
];

export function getPattern(id: DsaPatternId) {
  return DSA_PATTERNS.find((p) => p.id === id)!;
}

export function getProblem(id: string) {
  return DSA_PROBLEMS.find((p) => p.id === id);
}

export function problemsForWeek(week: number) {
  return DSA_PROBLEMS.filter((p) => p.week === week);
}

export function problemsForPattern(pattern: DsaPatternId) {
  return DSA_PROBLEMS.filter((p) => p.pattern === pattern);
}
